# Site settings
baseURL = "https://offering.solutions/"
languageCode = "en-us"
title = "Fabian Gosebrink Angular and ASP.NET Core Consulting, Training and Courses"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = "offeringsolutions"

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Fabian Gosebrink"
  description = "Angular and ASP.NET Core Consulting, Training and Courses"
  baseURLInternal = "/"
  # cdnbaseurl = "https://cdn.offering.solutions/"
  cdnbaseurl = "http://localhost:1313/"

  # Link custom assets relative to /static
  custom_css = ["css/custom.css", "css/scrolling.css"]
  custom_js  = ["js/search.js", "js/scrolling.js", "js/testimonials.js"]
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Offering Solutions Software"
    subtitle = "Fabian Gosebrink"
    menu = "Menu"
    # Optional logo as brand stored in img/
    logo = "offeringsolutions.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "Blog"
      url = "blog"

    [[params.navigation.links]]
      name = "Talks"
      url = "talks"

    [[params.navigation.links]]
      name = "Newsletter"
      url = "newsletter"

    [[params.navigation.links]]
      name = "Trainings"
      url = "trainings"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button2]]
      name = "To Personal Site"
      url = "https://fabian-gosebrink.com"

    # Button Style 2
   #  [[params.navigation.button2]]
   #    name = "Log In"
   #    url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Angular, ASP.NET Core & Azure Consulting"
    subtitle = "Offering Solutions Software"
    subtitle2 = "Microsoft MVP // Pluralsight Author // Google Developer Expert"
    buttonText = "See our Services"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Development"
      subtitle = "Offering ASP.NET Core and Angular Development"
      image = "landing/development.jpg"
      url = "#"

    [[params.tiles.showcase]]
      title = "Training"
      subtitle = "Get you and your team up and running in the latest web technologies with Angular, ASP.NET Core, Javascript and Typescript"
      image = "landing/training.jpg"
      url = "/trainings"

    [[params.tiles.showcase]]
      title = "Consulting"
      subtitle = "Latest info and Best Practices all around web technologies with Angular, ASP.NET Core, Javascript and Typescript"
      image = "landing/consulting.jpg"
      url = "#"

    [[params.tiles.showcase]]
      title = "Code Review"
      subtitle = "Let us discuss and talk about code..."
      image = "landing/review.jpg"
      url = "#"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "Blog"
    subtitle = "Latest articles about Angular and ASP.NET Core"
    buttonText = "To the blog"
    url = "blog"

  [params.trainings]
    enable = true
    buttonText = "To the workshops"
    url = "trainings"

  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    formEmail = "mail@offering.solutions"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "mail@offering.solutions"

    [[params.contact.phone]]
    title = "Phone"
    phone = "(000) 000-0000 x1234"

    [[params.contact.address]]
    title = "Address"
    name = "Offering Solutions Software GmbH"
    street = "Kesselhaldenstrasse 72"
    city = "9016 Sankt Gallen"
    country = "Switzerland"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Offering Solutions Software GmbH"

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://twitter.com/FabianGosebrink"
      label = "Twitter"

    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://twitter.com/OfferingSolu"
      label = "Twitter"

   [[params.footer.social]]
      icon = "fa-github"
      url= "https://github.com/FabianGosebrink"
      label = "GitHub"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://github.com/OfferingSolutions"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/fabian-gosebrink-71023a88"
      label = "LinkedIn"

    [[params.footer.social]]
      icon = "fa-xing"
      url= "https://www.xing.com/profile/Fabian_Gosebrink"
      label = "Xing"

    [[params.footer.social]]
      icon = "fa-windows"
      url= "https://mvp.microsoft.com/en-us/PublicProfile/5001666?fullName=Fabian%20%20Gosebrink"
      label = "Microsoft"

    [[params.footer.social]]
      icon = "fa-google"
      url= "https://developers.google.com/community/experts/directory/profile/profile-fabian_gosebrink"
      label = "Google"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"

    [[params.footer.quicklinks]]
      text = ""
      url= "/impressum"
      alt = "Impressum"

[permalinks]
  blog = "/blog/articles/:year/:month/:day/:title/"

[author]
  name = "Fabian Gosebrink"

[outputs]
  home = ["HTML", "RSS", "JSON"]

